# -*- coding: utf-8 -*-
"""Stringhe tradotte per le pagine app-ti-*.html — 14 lingue."""

LOCALE = {
    "ar": "ar_AR", "bn": "bn_BD", "de": "de_DE", "en": "en_US", "es": "es_ES",
    "fr": "fr_FR", "nl": "nl_NL", "pt": "pt_PT", "ro": "ro_RO", "sq": "sq_AL",
    "ti": "ti_ER", "tl": "tl_PH", "uk": "uk_UA", "zh": "zh_CN", "it": "it_IT",
}

# didascalie sotto gli screenshot, nell'ordine in cui compaiono
DIDASCALIE = {
    "it": ["Grammatica", "Percorso", "Edicola", "Lettura", "Parole crociate",
           "Coniugazioni", "Tappa completata", "Esame B1 cittadinanza", "Mappa",
           "Audio", "Progressi"],
    "en": ["Grammar", "Learning path", "Newsstand", "Reading", "Word search",
           "Conjugations", "Stage completed", "B1 citizenship exam", "Map",
           "Audio", "Progress"],
    "nl": ["Grammatica", "Traject", "Kiosk", "Lezen", "Woordzoeker",
           "Vervoegingen", "Etappe voltooid", "B1-examen staatsburgerschap", "Kaart",
           "Audio", "Voortgang"],
    "de": ["Grammatik", "Lernpfad", "Kiosk", "Lesen", "Buchstabengitter",
           "Konjugationen", "Etappe geschafft", "B1-Prüfung Staatsbürgerschaft", "Karte",
           "Audio", "Fortschritt"],
    "fr": ["Grammaire", "Parcours", "Kiosque", "Lecture", "Mots mêlés",
           "Conjugaisons", "Étape terminée", "Examen B1 citoyenneté", "Carte",
           "Audio", "Progression"],
    "es": ["Gramática", "Itinerario", "Quiosco", "Lectura", "Sopa de letras",
           "Conjugaciones", "Etapa completada", "Examen B1 de ciudadanía", "Mapa",
           "Audio", "Progreso"],
    "pt": ["Gramática", "Percurso", "Quiosque", "Leitura", "Caça-palavras",
           "Conjugações", "Etapa concluída", "Exame B1 de cidadania", "Mapa",
           "Áudio", "Progresso"],
    "ro": ["Gramatică", "Parcurs", "Chioșc", "Lectură", "Careu de cuvinte",
           "Conjugări", "Etapă încheiată", "Examen B1 cetățenie", "Hartă",
           "Audio", "Progres"],
    "sq": ["Gramatikë", "Rrugëtimi", "Kioska", "Lexim", "Fjalëkryq",
           "Zgjedhime", "Etapa u përfundua", "Provimi B1 për shtetësinë", "Harta",
           "Audio", "Përparimi"],
    "uk": ["Граматика", "Маршрут", "Кіоск", "Читання", "Пошук слів",
           "Дієвідміни", "Етап завершено", "Іспит B1 для громадянства", "Мапа",
           "Аудіо", "Прогрес"],
    "ar": ["القواعد", "المسار", "المكتبة", "القراءة", "البحث عن الكلمات",
           "تصريف الأفعال", "اكتملت المرحلة", "امتحان B1 للجنسية", "الخريطة",
           "الصوت", "التقدّم"],
    "bn": ["ব্যাকরণ", "পথ", "নিউজস্ট্যান্ড", "পড়া", "শব্দ খোঁজা",
           "ক্রিয়ার রূপ", "ধাপ সম্পূর্ণ", "নাগরিকত্বের B1 পরীক্ষা", "মানচিত্র",
           "অডিও", "অগ্রগতি"],
    "tl": ["Gramatika", "Landas", "Tindahan ng libro", "Pagbasa", "Hanap-salita",
           "Pagbabanghay", "Tapos na ang yugto", "Pagsusulit B1 para sa pagkamamamayan", "Mapa",
           "Audio", "Pag-unlad"],
    "ti": ["ሰዋስው", "መገሻ", "ኪዮስክ", "ንባብ", "ቃላት ምድላይ",
           "ኣገባብ ግሲ", "ደረጃ ተዛዚሙ", "ናይ ዜግነት B1 ፈተና", "ካርታ",
           "ድምጺ", "ምዕባለ"],
    "zh": ["语法", "学习路径", "书报亭", "阅读", "找单词",
           "动词变位", "阶段完成", "B1 入籍考试", "地图",
           "音频", "进度"],
}

# testi alternativi delle immagini: chiave = testo italiano originale
ALT = {
    "Il percorso di Ti su iPhone": {
        "en": "The Ti learning path on iPhone", "nl": "Het Ti-traject op iPhone",
        "de": "Der Ti-Lernpfad auf dem iPhone", "fr": "Le parcours Ti sur iPhone",
        "es": "El itinerario de Ti en iPhone", "pt": "O percurso do Ti no iPhone",
        "ro": "Parcursul Ti pe iPhone", "sq": "Rrugëtimi i Ti në iPhone",
        "uk": "Маршрут навчання Ti на iPhone", "ar": "مسار التعلّم في تطبيق Ti على iPhone",
        "bn": "আইফোনে Ti-এর শেখার পথ", "tl": "Ang landas ng pag-aaral ng Ti sa iPhone",
        "ti": "ናይ Ti መገሻ ትምህርቲ ኣብ iPhone", "zh": "iPhone 上的 Ti 学习路径",
    },
    "Grammatica: c'è / ci sono": {
        "en": "Grammar: c'è / ci sono", "nl": "Grammatica: c'è / ci sono",
        "de": "Grammatik: c'è / ci sono", "fr": "Grammaire : c'è / ci sono",
        "es": "Gramática: c'è / ci sono", "pt": "Gramática: c'è / ci sono",
        "ro": "Gramatică: c'è / ci sono", "sq": "Gramatikë: c'è / ci sono",
        "uk": "Граматика: c'è / ci sono", "ar": "القواعد: c'è / ci sono",
        "bn": "ব্যাকরণ: c'è / ci sono", "tl": "Gramatika: c'è / ci sono",
        "ti": "ሰዋስው፦ c'è / ci sono", "zh": "语法：c'è / ci sono",
    },
    "Percorso A1": {
        "en": "A1 learning path", "nl": "Traject A1", "de": "Lernpfad A1",
        "fr": "Parcours A1", "es": "Itinerario A1", "pt": "Percurso A1",
        "ro": "Parcurs A1", "sq": "Rrugëtimi A1", "uk": "Маршрут A1",
        "ar": "مسار المستوى A1", "bn": "A1 স্তরের পথ", "tl": "Landas A1",
        "ti": "መገሻ A1", "zh": "A1 学习路径",
    },
    "Edicola con romanzi e percorsi": {
        "en": "Newsstand with novels and learning paths",
        "nl": "Kiosk met romans en trajecten",
        "de": "Kiosk mit Romanen und Lernpfaden",
        "fr": "Kiosque avec romans et parcours",
        "es": "Quiosco con novelas e itinerarios",
        "pt": "Quiosque com romances e percursos",
        "ro": "Chioșc cu romane și parcursuri",
        "sq": "Kioska me romane dhe rrugëtime",
        "uk": "Кіоск із романами та маршрутами",
        "ar": "المكتبة مع الروايات والمسارات",
        "bn": "উপন্যাস ও শেখার পথ সহ নিউজস্ট্যান্ড",
        "tl": "Tindahan ng libro na may mga nobela at landas",
        "ti": "ኪዮስክ ምስ ልብወለዳትን መገሻታትን", "zh": "含小说与学习路径的书报亭",
    },
    "Lettore con dizionario integrato": {
        "en": "Reader with built-in dictionary", "nl": "Lezer met ingebouwd woordenboek",
        "de": "Lesemodus mit integriertem Wörterbuch", "fr": "Lecteur avec dictionnaire intégré",
        "es": "Lector con diccionario integrado", "pt": "Leitor com dicionário integrado",
        "ro": "Cititor cu dicționar integrat", "sq": "Lexues me fjalor të integruar",
        "uk": "Читалка з вбудованим словником", "ar": "قارئ مع قاموس مدمج",
        "bn": "অন্তর্নির্মিত অভিধানসহ রিডার", "tl": "Mambabasa na may kasamang diksiyonaryo",
        "ti": "ኣንባቢ ምስ ዝተወሃሃደ መዝገበ ቃላት", "zh": "内置词典的阅读器",
    },
    "Cruciverba": {
        "en": "Word search", "nl": "Woordzoeker", "de": "Buchstabengitter",
        "fr": "Mots mêlés", "es": "Sopa de letras", "pt": "Caça-palavras",
        "ro": "Careu de cuvinte", "sq": "Fjalëkryq", "uk": "Пошук слів",
        "ar": "البحث عن الكلمات", "bn": "শব্দ খোঁজার খেলা", "tl": "Hanap-salita",
        "ti": "ቃላት ምድላይ", "zh": "找单词游戏",
    },
    "Schede di vocabolario con pronuncia": {
        "en": "Vocabulary cards with pronunciation", "nl": "Woordkaarten met uitspraak",
        "de": "Vokabelkarten mit Aussprache", "fr": "Fiches de vocabulaire avec prononciation",
        "es": "Fichas de vocabulario con pronunciación", "pt": "Fichas de vocabulário com pronúncia",
        "ro": "Fișe de vocabular cu pronunție", "sq": "Skeda fjalori me shqiptim",
        "uk": "Картки слів із вимовою", "ar": "بطاقات مفردات مع النطق",
        "bn": "উচ্চারণসহ শব্দভান্ডার কার্ড", "tl": "Mga kard ng bokabularyo na may bigkas",
        "ti": "ካርድታት ቃላት ምስ ኣደማምጻ", "zh": "带发音的词汇卡片",
    },
    "Tappa completata con nota di grammatica": {
        "en": "Stage completed, with a grammar note", "nl": "Etappe voltooid, met grammaticanotitie",
        "de": "Etappe geschafft, mit Grammatiknotiz", "fr": "Étape terminée, avec une note de grammaire",
        "es": "Etapa completada, con nota de gramática", "pt": "Etapa concluída, com nota de gramática",
        "ro": "Etapă încheiată, cu notă de gramatică", "sq": "Etapa u përfundua, me shënim gramatikor",
        "uk": "Етап завершено, з нотаткою з граматики", "ar": "اكتملت المرحلة، مع ملاحظة نحوية",
        "bn": "ধাপ সম্পূর্ণ, ব্যাকরণ নোটসহ", "tl": "Tapos na ang yugto, may tala sa gramatika",
        "ti": "ደረጃ ተዛዚሙ፣ ምስ ናይ ሰዋስው መብርሂ", "zh": "阶段完成，附语法笔记",
    },
    "Simulazione esame B1 per la cittadinanza": {
        "en": "B1 citizenship exam simulation", "nl": "Simulatie B1-examen staatsburgerschap",
        "de": "Simulation der B1-Prüfung für die Staatsbürgerschaft",
        "fr": "Simulation de l'examen B1 pour la citoyenneté",
        "es": "Simulación del examen B1 de ciudadanía",
        "pt": "Simulação do exame B1 de cidadania",
        "ro": "Simulare examen B1 pentru cetățenie",
        "sq": "Simulim i provimit B1 për shtetësinë",
        "uk": "Симуляція іспиту B1 для громадянства",
        "ar": "محاكاة امتحان B1 للحصول على الجنسية",
        "bn": "নাগরিকত্বের B1 পরীক্ষার অনুশীলন",
        "tl": "Pagsasanay sa pagsusulit B1 para sa pagkamamamayan",
        "ti": "ናይ ዜግነት B1 ፈተና ልምምድ", "zh": "B1 入籍考试模拟",
    },
    "Mappa dell'Italia con le regioni": {
        "en": "Map of Italy with the regions", "nl": "Kaart van Italië met de regio's",
        "de": "Karte Italiens mit den Regionen", "fr": "Carte de l'Italie avec les régions",
        "es": "Mapa de Italia con las regiones", "pt": "Mapa da Itália com as regiões",
        "ro": "Harta Italiei cu regiunile", "sq": "Harta e Italisë me rajonet",
        "uk": "Мапа Італії з регіонами", "ar": "خريطة إيطاليا مع المناطق",
        "bn": "অঞ্চলসহ ইতালির মানচিত্র", "tl": "Mapa ng Italya kasama ang mga rehiyon",
        "ti": "ካርታ ኢጣልያ ምስ ዞባታታ", "zh": "标注各大区的意大利地图",
    },
    "Ascolto con audio nativo": {
        "en": "Listening with native audio", "nl": "Luisteren met audio van moedertaalsprekers",
        "de": "Hörverstehen mit muttersprachlichem Audio", "fr": "Écoute avec audio de locuteurs natifs",
        "es": "Comprensión oral con audio nativo", "pt": "Compreensão oral com áudio nativo",
        "ro": "Ascultare cu audio nativ", "sq": "Dëgjim me audio nga folës vendas",
        "uk": "Аудіювання з озвученням носіїв мови", "ar": "استماع بصوت متحدثين أصليين",
        "bn": "স্থানীয় ভাষাভাষীর অডিওসহ শোনা", "tl": "Pakikinig gamit ang audio ng katutubong nagsasalita",
        "ti": "ምስማዕ ብድምጺ ወለንተኛታት ተዛረብቲ", "zh": "母语者音频听力",
    },
    "Report dei progressi": {
        "en": "Progress report", "nl": "Voortgangsrapport", "de": "Fortschrittsbericht",
        "fr": "Rapport de progression", "es": "Informe de progreso", "pt": "Relatório de progresso",
        "ro": "Raport de progres", "sq": "Raporti i përparimit", "uk": "Звіт про прогрес",
        "ar": "تقرير التقدّم", "bn": "অগ্রগতির রিপোর্ট", "tl": "Ulat ng pag-unlad",
        "ti": "ጸብጻብ ምዕባለ", "zh": "学习进度报告",
    },
    "Livelli A1-C2 con parola del giorno": {
        "en": "A1–C2 levels with the word of the day", "nl": "Niveaus A1–C2 met het woord van de dag",
        "de": "Niveaus A1–C2 mit dem Wort des Tages", "fr": "Niveaux A1–C2 avec le mot du jour",
        "es": "Niveles A1–C2 con la palabra del día", "pt": "Níveis A1–C2 com a palavra do dia",
        "ro": "Niveluri A1–C2 cu cuvântul zilei", "sq": "Nivelet A1–C2 me fjalën e ditës",
        "uk": "Рівні A1–C2 зі словом дня", "ar": "المستويات A1–C2 مع كلمة اليوم",
        "bn": "দিনের শব্দসহ A1–C2 স্তর", "tl": "Mga antas A1–C2 na may salita ng araw",
        "ti": "ደረጃታት A1–C2 ምስ ቃል መዓልቲ", "zh": "A1–C2 等级与每日单词",
    },
    "Edicola": {
        "en": "Newsstand", "nl": "Kiosk", "de": "Kiosk", "fr": "Kiosque",
        "es": "Quiosco", "pt": "Quiosque", "ro": "Chioșc", "sq": "Kioska",
        "uk": "Кіоск", "ar": "المكتبة", "bn": "নিউজস্ট্যান্ড", "tl": "Tindahan ng libro",
        "ti": "ኪዮስክ", "zh": "书报亭",
    },
    "Romanzo classico": {
        "en": "A classic novel", "nl": "Een klassieke roman", "de": "Ein klassischer Roman",
        "fr": "Un roman classique", "es": "Una novela clásica", "pt": "Um romance clássico",
        "ro": "Un roman clasic", "sq": "Një roman klasik", "uk": "Класичний роман",
        "ar": "رواية كلاسيكية", "bn": "একটি ধ্রুপদী উপন্যাস", "tl": "Isang klasikong nobela",
        "ti": "ክላሲካዊ ልብወለድ", "zh": "经典小说",
    },
    "Grammatica multilingua": {
        "en": "Grammar in many languages", "nl": "Grammatica in meerdere talen",
        "de": "Grammatik in mehreren Sprachen", "fr": "Grammaire en plusieurs langues",
        "es": "Gramática en varios idiomas", "pt": "Gramática em várias línguas",
        "ro": "Gramatică în mai multe limbi", "sq": "Gramatikë në disa gjuhë",
        "uk": "Граматика кількома мовами", "ar": "القواعد بعدّة لغات",
        "bn": "একাধিক ভাষায় ব্যাকরণ", "tl": "Gramatika sa maraming wika",
        "ti": "ሰዋስው ብብዙሓት ቋንቋታት", "zh": "多语言语法讲解",
    },
}

# og:description e twitter:description
DESCRIZIONE = {
    "en": "iOS app to learn Italian from A1 to C2. CEFR path, themed newsstand, graded novels, multilingual dictionary. Support in 14 languages for foreigners and migrants.",
    "nl": "iOS-app om Italiaans te leren van A1 tot C2. ERK-traject, thematische kiosk, romans op niveau, meertalig woordenboek. Ondersteuning in 14 talen voor buitenlanders en migranten.",
    "de": "iOS-App, um Italienisch von A1 bis C2 zu lernen. GER-Lernpfad, thematischer Kiosk, abgestufte Romane, mehrsprachiges Wörterbuch. Unterstützung in 14 Sprachen für Ausländer und Migranten.",
    "fr": "Application iOS pour apprendre l'italien de A1 à C2. Parcours CECRL, kiosque thématique, romans gradués, dictionnaire multilingue. Support en 14 langues pour étrangers et migrants.",
    "es": "App iOS para aprender italiano de A1 a C2. Itinerario MCER, quiosco temático, novelas graduadas, diccionario multilingüe. Apoyo en 14 idiomas para extranjeros y migrantes.",
    "pt": "App iOS para aprender italiano de A1 a C2. Percurso QECR, quiosque temático, romances graduados, dicionário multilingue. Apoio em 14 línguas para estrangeiros e migrantes.",
    "ro": "Aplicație iOS pentru a învăța italiana de la A1 la C2. Parcurs CECRL, chioșc tematic, romane gradate, dicționar multilingv. Sprijin în 14 limbi pentru străini și migranți.",
    "sq": "Aplikacion iOS për të mësuar italishten nga A1 në C2. Rrugëtim sipas KEGJ, kioskë tematike, romane të graduara, fjalor shumëgjuhësh. Mbështetje në 14 gjuhë për të huaj dhe migrantë.",
    "uk": "Застосунок для iOS, щоб вивчити італійську від A1 до C2. Маршрут за CEFR, тематичний кіоск, адаптовані романи, багатомовний словник. Підтримка 14 мовами для іноземців і мігрантів.",
    "ar": "تطبيق iOS لتعلّم الإيطالية من A1 إلى C2. مسار وفق الإطار الأوروبي، مكتبة موضوعية، روايات مبسّطة، قاموس متعدّد اللغات. دعم بـ14 لغة للأجانب والمهاجرين.",
    "bn": "A1 থেকে C2 পর্যন্ত ইতালীয় শেখার iOS অ্যাপ। CEFR পথ, বিষয়ভিত্তিক নিউজস্ট্যান্ড, স্তরভিত্তিক উপন্যাস, বহুভাষিক অভিধান। বিদেশি ও অভিবাসীদের জন্য ১৪টি ভাষায় সহায়তা।",
    "tl": "iOS app para matuto ng Italyano mula A1 hanggang C2. Landas ayon sa CEFR, tindahan ng libro ayon sa tema, mga nobelang naka-antas, diksiyonaryong maraming wika. Suporta sa 14 na wika para sa mga dayuhan at migrante.",
    "ti": "ጣልያንኛ ካብ A1 ክሳብ C2 ንምምሃር ናይ iOS መተግበሪ። ብCEFR ዝተመርሐ መገሻ፣ ብቴማ ዝተኸፍለ ኪዮስክ፣ ብደረጃ ዝተዳለዉ ልብወለዳት፣ ብዙሕ ቋንቋ መዝገበ ቃላት። ን14 ቋንቋታት ደገፍ ንወጻእተኛታትን ስደተኛታትን።",
    "zh": "从 A1 到 C2 学习意大利语的 iOS 应用。CEFR 学习路径、主题书报亭、分级小说、多语言词典。为外国人和移民提供 14 种语言支持。",
}

# disclaimer sui marchi delle certificazioni
DISCLAIMER = {
    "en": "CILS, CELI and PLIDA are registered trademarks of their respective owners (University for Foreigners of Siena, University for Foreigners of Perugia, Società Dante Alighieri). Ti and thuisitaliaans are not affiliated with, sponsored or endorsed by these bodies; the names are used for identification purposes only.",
    "nl": "CILS, CELI en PLIDA zijn geregistreerde handelsmerken van hun respectieve eigenaars (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti en thuisitaliaans zijn niet verbonden aan deze instanties en worden er niet door gesponsord of goedgekeurd; de namen worden uitsluitend ter identificatie genoemd.",
    "de": "CILS, CELI und PLIDA sind eingetragene Marken der jeweiligen Inhaber (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti und thuisitaliaans sind mit diesen Einrichtungen weder verbunden noch von ihnen gesponsert oder anerkannt; die Namen dienen ausschließlich der Identifikation.",
    "fr": "CILS, CELI et PLIDA sont des marques déposées de leurs titulaires respectifs (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti et thuisitaliaans ne sont ni affiliés à ces organismes, ni sponsorisés ou approuvés par eux ; les noms sont cités à seule fin d'identification.",
    "es": "CILS, CELI y PLIDA son marcas registradas de sus respectivos titulares (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti y thuisitaliaans no están afiliados a estas entidades ni patrocinados o aprobados por ellas; los nombres se citan únicamente con fines identificativos.",
    "pt": "CILS, CELI e PLIDA são marcas registadas dos respetivos titulares (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti e thuisitaliaans não estão associados a estas entidades nem são por elas patrocinados ou aprovados; os nomes são citados apenas para fins de identificação.",
    "ro": "CILS, CELI și PLIDA sunt mărci înregistrate ale titularilor respectivi (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti și thuisitaliaans nu sunt afiliate acestor instituții și nici sponsorizate sau aprobate de ele; numele sunt citate exclusiv în scop de identificare.",
    "sq": "CILS, CELI dhe PLIDA janë marka të regjistruara të pronarëve përkatës (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti dhe thuisitaliaans nuk janë të lidhura me këto institucione dhe as të sponsorizuara apo të miratuara prej tyre; emrat përmenden vetëm për qëllime identifikimi.",
    "uk": "CILS, CELI та PLIDA є зареєстрованими торговими марками відповідних власників (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ti і thuisitaliaans не пов'язані з цими установами, не спонсоруються та не схвалені ними; назви наведено виключно для ідентифікації.",
    "ar": "‏CILS وCELI وPLIDA علامات تجارية مسجّلة لأصحابها (Università per Stranieri di Siena، Università per Stranieri di Perugia، Società Dante Alighieri). لا يرتبط تطبيق Ti ولا موقع thuisitaliaans بهذه الجهات، وليسا برعايتها أو بموافقتها؛ وتُذكر الأسماء لغرض التعريف فقط.",
    "bn": "CILS, CELI ও PLIDA তাদের নিজ নিজ মালিকের নিবন্ধিত ট্রেডমার্ক (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri)। Ti ও thuisitaliaans এই প্রতিষ্ঠানগুলোর সঙ্গে যুক্ত নয়, তাদের দ্বারা পৃষ্ঠপোষকতাপ্রাপ্ত বা অনুমোদিতও নয়; নামগুলো কেবল শনাক্তকরণের উদ্দেশ্যে উল্লেখ করা হয়েছে।",
    "tl": "Ang CILS, CELI at PLIDA ay mga rehistradong trademark ng kani-kanilang may-ari (Università per Stranieri di Siena, Università per Stranieri di Perugia, Società Dante Alighieri). Ang Ti at thuisitaliaans ay hindi kaugnay, hindi isinusuportahan at hindi inaprubahan ng mga institusyong ito; binanggit ang mga pangalan para lamang sa pagkakakilanlan.",
    "ti": "CILS፣ CELI ከምኡ'ውን PLIDA ናይ በዓል ዋናታቶም ዝተመዝገቡ ንግዳዊ ምልክታት እዮም (Università per Stranieri di Siena፣ Università per Stranieri di Perugia፣ Società Dante Alighieri)። Ti ከምኡ'ውን thuisitaliaans ምስዞም ትካላት ርክብ የብሎምን፣ ብኣታቶም'ውን ኣይተደገፉን ኣይተፈቕዱን፤ ስማት ንመለለዪ ጥራይ ተጠቒሶም ኣለዉ።",
    "zh": "CILS、CELI 和 PLIDA 是各自所有者的注册商标（锡耶纳外国人大学、佩鲁贾外国人大学、但丁协会）。Ti 与 thuisitaliaans 与上述机构无隶属关系，也未获其赞助或认可；提及这些名称仅用于识别目的。",
}


# chiave mancante dal dizionario delle pagine
CONIUGAZIONI = {
    "it": "Coniugazioni", "en": "Conjugations", "nl": "Vervoegingen",
    "de": "Konjugationen", "fr": "Conjugaisons", "es": "Conjugaciones",
    "pt": "Conjugações", "ro": "Conjugări", "sq": "Zgjedhime",
    "uk": "Дієвідміни", "ar": "تصريف الأفعال", "bn": "ক্রিয়ার রূপ",
    "tl": "Pagbabanghay", "ti": "ኣገባብ ግሲ", "zh": "动词变位",
}
